@extends('master')

@section('content')
<body>
    <div class="background">

        <div class="container">
            <div class="fs-s"></div>
            <div data-aos="fade-up" data-aos-duration="800">
                <h1 class="text-center text-medium">Become an Enterprise user today!</h1>
                <p class="textmuted text-center">All membership packages come with a 30-day satisfaction guarantee.</p>
            </div>


            <div class="fs-m"></div>
            <div class="row">
                <div class="col-sm-4" data-aos="fade-right" data-aos-duration="700">
                    <div class="enterprise-ad">
                        <h4>Enterpriser basic</h4>
                        <h3>€34,99 <span class="desc">per month</span></h3>

                        <p>For those really serious in search of true IT love, supported with the <b>latest technology</b> from Digidate.</p>
                        <hr>
                        <ul>
                            <li>Cool Enterprise badge on profile</li>
                            <li>Deploy from CLI or personal git integrations</li>
                            <li>Automatic HTTPS/SSL</li>
                        </ul>

                        <br>

                        <div class="row row justify-content-center">
                            @auth
                                <a href="{{ route('enterprise.show', 0) }}">
                                    <button class="btn btn-outline-dark btn-lg">Get basic now</button>
                                </a>
                            @endauth
                            @guest()
                                <a href="{{ route('register') }}">
                                    <button class="btn btn-outline-dark btn-lg">Get basic now</button>
                                </a>
                            @endguest
                        </div>

                    </div>
                </div>
                <div class="col-sm-4" data-aos="fade-up" data-aos-duration="700">
                    <div class="enterprise-ad" id="premium">
                        <h4>Enterpriser <span class="charm-1">Premium</span></h4>
                        <h3>€39,99 <span class="desc">per month</span></h3>

                        <p>For those really serious in search of true IT love, supported with the <b>latest technology</b> from Digidate.</p>
                        <hr>
                        <ul>
                            <li>Chat sentences generated by ChatGPT-4</li>
                            <li>Enhanced observability & logging</li>
                            <li>Up to 1TB of bandwidth</li>
                        </ul>

                        <br>

                        <div class="row row justify-content-center">
                            @auth
                                <a href="{{ route('enterprise.show', 1) }}">
                                    <button class="btn btn-outline-danger btn-lg">Get Premium now</button>
                                </a>
                            @endauth
                            @guest()
                                <a href="{{ route('register') }}">
                                    <button class="btn btn-outline-danger btn-lg">Get Premium now</button>
                                </a>
                            @endguest
                        </div>

                    </div>
                </div>
                <div class="col-sm-4" data-aos="fade-left" data-aos-duration="700">
                    <div class="enterprise-ad" id="diamond">
                        <h4>Enterpriser <span class="charm-2">Diamond</span></h4>
                        <h3>€44,99 <span class="desc">per month</span></h3>

                        <p>For those really serious in search of true IT love, supported with the <b>latest technology</b> from Digidate.</p>
                        <hr>
                        <ul>
                            <li>Liked randomizer priority</li>
                            <li>See who liked your profile</li>
                            <li>Free keyboard sent to your doorstep</li>
                        </ul>

                        <br>

                        <div class="row row justify-content-center">
                            @auth
                                <a href="{{ route('enterprise.show', 2) }}">
                                    <button class="btn btn-outline-primary btn-lg">Get Diamond now</button>
                                </a>
                            @endauth
                            @guest()
                                <a href="{{ route('register') }}">
                                    <button class="btn btn-outline-primary btn-lg">Get Diamond now</button>
                                </a>
                            @endguest
                        </div>

                    </div>
                </div>
            </div>
        </div>

        <div class="fs-l"></div>

        <div class="container" data-aos="fade-up" data-aos-duration="800">
            <h1 class="text-center">
                Become better than <i>basic</i>
            </h1>
            <p class="text-center-desc">
                Our services provide the best of best quality of code (by Mark Zuckerberg from Facebook, Meta), <br>
                with countless of dope ass features that will lead you to your dream IT waifu.
            </p>
        </div>

        <div class="fs-l"></div>

        <div class="container">
            <h1 class="text-center" data-aos="fade-up" data-aos-duration="700">"Best service ever made holy sh*t"</h1>
            <p class="text-center-desc" data-aos="fade-up" data-aos-duration="800" data-aos-delay="200">
                <i>"This is the best service of dating apps ever made holy sh*t"</i>, stated Elon Ma, richest man alive on planet earth (and universe).
                <br>
                <i>"I got my first match on this website as fast as our newest Tesla Roadster that goes from 0 to 100 in 2.1 seconds."</i>
            </p>
        </div>

        <div class="fs-l"></div>

        <div class="container">
            <h1 class="text-center" data-aos="fade-up" data-aos-duration="700">Powered by OpenAI's Chat-GPT gen 4</h1>
            <p class="text-center-desc" data-aos="fade-up" data-aos-duration="800" data-aos-delay="200">
                DigiDate utilizes the power of AI, as it's booming in the industry right now. <br>
                Chat-GPT is your companion to reeling in girls into your DMs, with starting sentences where you will be unstoppable in the battlefield.
            </p>
        </div>

        <div class="fs-l"></div>

    </div>
</body>
@endsection
