@extends('master')

@section('content')
<body>
<div class="background">
    <div class="container">
        <div class="row">
            <div class="col-sm-5">
                <h2>{{ $greet }}</h2>
                <div class="fs-m"></div>
                <div class="enterprise-ad">
                    <h3>Become Enterpriser!</h3>
                    <hr>
                    <p>Get the following benefits:</p>

                    <li>Chat sentences generated by ChatGPT-4</li>
                    <li>Liked randomizer priority</li>
                    <li>Cool Enterprise badge on profile</li>
                    <li>Dark mode for the application</li>

                    <br>

                    <p>Subscription prices:</p>

                    <h3>P/month: €44,99</h3>
                    <h3>P/year: <s class="red">€539,99</s> €377,99<span class="percen">-30%</span></h3>

                    <br>

                    <a href="#">
                        <button class="btn btn-m btn-success">Get Enterprise now</button>
                    </a>
                </div>
            </div>
            <div class="col-sm-7">
                <h2 class="align-l">Recent activity</h2>
                <div class="fs-s"></div>
                {{-- foreach will be placed here, for overall activity for the user --}}
                <div class="activity-block">
                    <div class="container">
                        <div class="row">
                            <div class="col-sm-2">
                                <img class="round activity-img mx-auto" src="{{ asset('media/joebiden.jpg') }}" alt="user" />
                            </div>
                            <div class="col-sm">
                                <h3>Interaction</h3>
                                <p>Joe Biden has liked your profile!</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="fs-xxs"></div>
                {{-- foreach will end here --}}

                {{-- an if statement or some sort, for a non enterprise user --}}
                <div class="activity-block">
                    <div class="container">
                        <div class="row">
                            <div class="col-sm-2">
                                <img class="round blurred activity-img mx-auto" src="{{ asset('media/joebiden.jpg') }}" alt="user" />
                            </div>
                            <div class="col-sm">
                                <h3>Interaction</h3>
                                <p><a style="text-decoration: none" href="{{ route('enterprise.index') }}">---------</a> has liked your profile!</p>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
    <div class="fs-s"></div>
</div>
</body>
@endsection
