@extends('master')

@section('content')
<body>
    <div class="background">
        <img src="{{ asset('../media/love.jpg') }}" alt="" width="100%" height="auto">
        <div class="fs-s"></div>
            <div class="container" data-aos="fade-up" data-aos-duration="800">
                <h1 class="text-center">
                    Welcome to <b>DigiDate</b>
                </h1>
                <p class="text-center-desc">
                    The <b>ultimate</b> utility site to finding your true love. <br>
                    Scroll down to find more about our service.
                </p>
            </div>

            <div class="fs-l"></div>

            <div class="container">
                <h1 class="text-center" data-aos="fade-up" data-aos-duration="700">Find your <i>hello</i> to your <i>world</i>.</h1>
                <p class="text-center-desc" data-aos="fade-up" data-aos-duration="800" data-aos-delay="200">
                    DigiDate provides easier opportunities for developers to find their love of their life. <br> With our
                    advanced algorithms it makes matching for our users very easy to use, which has pleased dozens of users
                    to find their partner.
                </p>
            </div>

            <div class="fs-l"></div>

            <div class="container">
                <h1 class="text-center" data-aos="fade-up" data-aos-duration="700">Get even <b>more</b> with <i>Enterprise</i></h1>
                <p class="text-center-desc" data-aos="fade-up" data-aos-duration="800" data-aos-delay="200">
                    DigiDate has it's premium tier called 'Enterprise' that comes with a handful of benefits such as:
                    <br>
                    -> Preset sentences generated by the AI GPT-3 <br>
                    -> Highlighted as top 1% for your potential match <br>
                    -> Special badge next to your profile.
                </p>
            </div>

            <div class="fs-l"></div>

            <div class="container">
                <h1 class="text-center" data-aos="fade-up" data-aos-duration="700">Wait no more, <i>deploy</i> now!</h1>
                <p class="text-center-desc" data-aos="fade-up" data-aos-duration="800" data-aos-delay="200">
                    Deploying right now increases your chances of marrying your programming partner.
                </p>
                <div class="fs-s"></div>

                <a href="{{ url('/register') }}">
                    <div class="text-center">
                        <button class="btn btn-lg btn-primary">Get started!</button>
                    </div>
                </a>
            </div>

            <div class="fs-xl"></div>
    </div>
</body>
@endsection
